language: python
sudo: required
python:
  - 2.7
script:
  - pip install PyWebRunner
  - webrunner google.yml
before_script:
  - sudo apt-get -y purge chromium-browser
  - curl -L -O "http://chromedriver.storage.googleapis.com/2.23/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip && chmod +x chromedriver && sudo mv chromedriver /usr/local/bin
  - export CHROMEDRIVER_VERSION=2.23
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
